services:
  robotics_env:
    build: 
      context: .
      dockerfile: Dockerfile
      # Use the same user and group IDs as the host user. This will ensure that
      # permissions are consistent inside and outside the container.
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USERNAME=${USERNAME:-user}
    hostname: docker

    # Interactive terminal
    stdin_open: true
    tty: true

    # Network for ROS 2
    network_mode: host

    # Allow GUI applications
    environment:
      - DISPLAY=${DISPLAY}

    # Bind mount so that source code changes outside the container are reflected
    # inside it, and vice versa.
    volumes:
      - ./src/course_pkg:/home/${USERNAME}/ros2_ws/src/course_pkg
